config/routes.rb
Rails.application.routes.draw do
  # devise_for :users

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', registration: '', sign_up: 'register' }, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        passwords: 'users/passwords'
      }
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
  end


  root 'books#index'
  resources :books do
    resources :publishers
    resources :authors
  end

  resources :categories
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/author.rb
class Author < ApplicationRecord

  validates :name, :email, presence: true, uniqueness: true

  belongs_to :book
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

	before_action :set_book , only: [:create, :edit, :update, :destroy]
	before_action :set_author , only: [:edit, :update, :destroy]


	def new
		setPageTitle "New author"
		@author = Author.new
		authorize @author
	end

	def create
		@author = Author.new(author_params)
		@author.book = @book
		if @author.save
			flash[:notice] = "#{@book.title} Author is created"
			redirect_to @book
		else
			flash[:alert] = "Unable to create Author"
			render :new, status: :unprocessable_entity
		end
	end

	def edit
		setPageTitle @author.name
	end

	def update
		if @author.update(author_params)
			flash[:notice] = "#{@book.title} Author is updated"
			redirect_to @book
		else
			flash[:alert] = "Unable to update Author"
			render :edit
		end
	end


	def destroy

		if @author.destroy
			flash[:notice] = "#{@book.title} Author is deleted"
		end
		redirect_to @book

	end

	private

	def author_params
		params.require(:author).permit(:name, :email)
	end

	def set_book
		@book = Book.friendly.find(params[:book_id])
	end

	def set_author
		@author = Author.find(params[:id])
		authorize @author
	end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.erb
<h1><%= heading %></h1>
<%= form_with model: @author, url: url do |form| %>
	<div class="mt-3">
		<%= form.label :name ,class:"form-control border-0", style:"background: chocolate;"%>
		<%= form.text_field :name ,class:"form-control"%>
	</div>
	<div class="mt-3">
		<%= form.label :email ,class:"form-control border-0", style:"background: chocolate;"%>
		<%= form.text_field :email ,class:"form-control"%>
	</div>
	<%= form.submit class:"btn btn-outline-primary mt-3" %>
	<%= link_to :back, :back , class:"btn btn-outline-info mt-3" %>
<% end %>

app/views/authors/edit.html.erb
<div class="container">
	<div class="col-lg-6">
		<%= render 'form', author: @author , url: book_author_path(params[:book_id]) , heading: "Edit Author" %>
	</div>
</div>

app/views/authors/new.html.erb
<div class="container">
	<div class="col-lg-6">
		<%= render 'form', author: @author , url: book_authors_path(params[:book_id]), heading: "Create New Author" %>
	</div>
</div>