config/routes.rb
Rails.application.routes.draw do
  # devise_for :users

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', registration: '', sign_up: 'register' }, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        passwords: 'users/passwords'
      }
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
  end


  root 'books#index'
  resources :books do
    resources :publishers
    resources :authors
  end

  resources :categories
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/shared/_alert.html.erb
<% if notice.present? %>
	<div class="alert alert-p alert-dismissible fade show messages">
		<strong><%= notice %></strong>
		<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
	</div>
<% end %>
<% if alert.present? %>
	<div class="alert alert-danger alert-dismissible fade show messages">
		<strong><%= alert %></strong>
		<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
	</div>
<% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" >
  <div class="container-fluid">
    <%= link_to "Home" , root_path, class:"navbar-brand"  %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <!-- <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li> -->
        <% if user_signed_in? %>
          <% if current_user.Admin? %>
            <li class="nav-item">
              <%= link_to "Catagoty", categories_path, class:"nav-link" %>
            </li>
          <% end %>
          <li class="nav-item">
            <%#= link_to "New book", new_book_path,class:"nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Book
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <% unless params[:action]=='new' %>
                <li><%= link_to "New book", new_book_path,class:"dropdown-item" %></li>
                <li><hr class="dropdown-divider"></li>
              <% end %>
               <!-- <li><a class="dropdown-item" href="#">Another action</a></li>  -->
              <li><%= link_to "Book List", root_path, class:"dropdown-item" %></li>
            </ul>
          </li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <%= navigation_link%>
      </ul>
      <!-- <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form> -->
    </div>
  </div>
</nav>