config/routes.rb
Rails.application.routes.draw do
  # devise_for :users

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', registration: '', sign_up: 'register' }, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        passwords: 'users/passwords'
      }
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
  end


  root 'books#index'
  resources :books do
    resources :publishers
    resources :authors
  end

  resources :categories
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/book.rb
class Book < ApplicationRecord
	validates :title, :desc, :price, :page, presence: true
	validates :title, uniqueness: true
	validates :user_id, presence: true

	mount_uploader :cover, CoverUploader
	has_one_attached :book_pdf

	extend FriendlyId
	friendly_id :title, use: :slugged

	has_one :publisher
	has_many :authors

	has_many :category_books
	has_many :categories, through: :category_books

	belongs_to :user

	paginates_per 9

	def delete
		if self.publisher.present?
			self.publisher.destroy
		end

		if self.authors.present?
			self.authors.destroy_all
		end
		if self.categories.present?
			self.categories.each do |category|
				category.books.destroy(self)
			end
		end
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]
  before_action :authenticate_user! , except: [:index,:show]

  # GET /books or /books.json
  def index
    setPageTitle "Books"
    @books = Book.all.page(params[:page])
  end

  # GET /books/1 or /books/1.json
  def show
    setPageTitle @book.title
  end

  # GET /books/new
  def new
    setPageTitle "New"
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
    setPageTitle "#{@book.title}"
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "Book was successfully created."
      redirect_to @book
    else
      flash[:alert] = "Unable to create book"
      render :new, status: :unprocessable_entity
    end
    # respond_to do |format|
    #   if @book.save
    #     format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
    #     format.json { render :show, status: :created, location: @book }
    #   else
    #     format.html { render :new, status: :unprocessable_entity }
    #     format.json { render json: @book.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        flash[:alert] = "Unable to update book"
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.delete
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.friendly.find(params[:id])
      authorize @book
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:cover,:book_pdf, :title, :desc, :price, :page, category_ids:[])
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/shared/books/_author.html.erb
<div class="card w-100 mb-3">
  <div class="catd-title  text-center">
    <h1>Authors List</h1>
  </div>
  <div class="card-body">
    <table class="table">
    	<p class="float-start"><%= link_to '<i class="fa fa-solid fa-plus fa-lg"></i>'.html_safe, new_book_author_path(book)%> Add Author</p>
      <thead>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <% book.authors.each do |author| %>
          <tr>
            <td><%= author.name %></td>
            <td><%= author.email %></td>
            <td>
              <%= link_to "<i class='fa fa-solid fa-pencil fa-lg'></i>".html_safe , edit_book_author_path(book, author),class:"mx-3"%>
              <%= link_to '<i class="fa fa-regular fa-trash fa-lg" style="color: #ff2424;"></i>'.html_safe, book_author_path(book, author), method: :delete, data: {confirm: "Are You Sure?"}  %></td>
          </tr>  
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/shared/books/_book.html.erb
<div class="card w-100 mb-3">
  <div class="card-title  text-center">
    <h1><%= book.title %></h1>
  </div>
  <div class="card-body">
    <p class="float-end"><%= link_to "<i class='fa fa-solid fa-pencil fa-lg'></i>".html_safe , edit_book_path(book)  %></p>
    <strong>Description :- <%= book.desc %></strong>
    <p> Price :- <%= book.price %><br>
     Page :- <%= book.page %> </p>
     <p>
     <strong> Uploaded By:- </strong>
     <%= book.user.email %></p>

    <%= render "shared/books/categories", book: @book %>
     
  </div>
</div>

app/views/shared/books/_categories.html.erb
<strong>Categories :</strong>

<% @book.categories.each do |category| %>
	<%= link_to "#{category.name}" ,category , class:"text-decoration-none link-dark hoverable view overlay zoom mx-2" %>
<% end %>

app/views/shared/books/_publisher.html.erb
<% if book.publisher.present? %>
	<div class="card w-100 mb-3">
		<div class="card-title  text-center">
			<h1>Publisher Info</h1>
		</div>
		<div class="card-body">
			<p class="float-end"><%= link_to "<i class='fa fa-solid fa-pencil fa-lg'></i>".html_safe, edit_book_publisher_path(book.id, book.publisher.id)  %></p>
			<strong>Publisher :- <%= book.publisher.publish %></strong>
			<p> Address :- <%= book.publisher.address %></p>
		</div>
	</div>
<%else%>
	<div class="card w-100 mb-3">
		<div class="card-title  text-center">
			<h1>Publisher Info</h1>
		</div>
		<div class="card-body">
			<p class="float-end"><%= link_to '<i class="fa fa-solid fa-plus fa-lg"></i>'.html_safe, new_book_publisher_path(book)  %></p>
			<strong>No Publisher Found</strong>
		</div>
	</div>
<%end%>

app/views/shared/books/_show_book.html.erb
<a href="<%= book_path(book) %>", class="text-decoration-none">
	<div class="card mx-2" style="height: 100%;width: 320px;background: #C19314;">
		<div class="card-body">
			<div class="container">
				<% if book.cover? %>
					<%= image_tag book.cover_url, class:"card-img-top", style: 'height:320px;width:100%;' %>
				<% else %>
					<%= image_tag 'cover', style: 'height:320px;width:100%;' %>
				<% end %>
				<h4><%= book.title %></h4>
			</div>
		</div>
	</div>
</a>